Feature ETP-713: Added base builder for the toolbar
etendosoftware/com.etendoerp.metadata pull request #6
Opened 2024-11-08 03:06 UTC by Sankku

2024-11-15 17:11 UTC, LuuchoRocha requested changes

2024-11-15 17:11 UTC, LuuchoRocha commented on src/com/etendoerp/metadata/MetadataServlet.java
> +                sendErrorResponse(response, HttpServletResponse.SC_NOT_FOUND, e.getMessage());
Please, create a new exception called `UnprocessableContentException`.
Remove this sendErrorResponse and instead use:

`throw new UnprocessableContentException(e.getMessage());`

you will need to update the `getResponseStatus` of `BaseServlet`:


```
    protected int getResponseStatus(Exception e) {
        Object clazz = e.getClass();

        if (clazz.equals(OBSecurityException.class) || clazz.equals(UnauthorizedException.class)) return 401;
        else if (clazz.equals(MethodNotAllowedException.class)) return 405;
        else if (clazz.equals(UnprocessableContentException.class)) return 422;
        else return 500;
    }
```

2024-11-15 17:11 UTC, LuuchoRocha commented on src/com/etendoerp/metadata/MetadataServlet.java
> +                sendErrorResponse(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Error processing request");
```suggestion
                new InternalServerException();
```

2024-11-15 17:11 UTC, LuuchoRocha commented on src/com/etendoerp/metadata/builders/ToolbarBuilder.java
> +            throw new RuntimeException("Failed to build toolbar", e);
Please use more specific exceptions

2024-11-15 17:11 UTC, LuuchoRocha commented on src/com/etendoerp/metadata/builders/ToolbarBuilder.java
> +    }
```suggestion
    private JSONObject createButtonJSON(ButtonConfig config) throws Exception {
        JSONObject button = new JSONObject();

        button.put("id", config.id);
        button.put("name", Utility.messageBD(connectionProvider, config.name, language));
        button.put("action", config.action);
        button.put("enabled", config.enabled);
        button.put("visible", true);
        button.put("icon", config.icon);

        return button;
    }
```

2024-11-15 17:11 UTC, LuuchoRocha commented on src/com/etendoerp/metadata/builders/ToolbarBuilder.java
> +    }
```suggestion
    private Map<String, ButtonConfig> getStandardButtons() {
        Map<String, ButtonConfig> buttons = new HashMap<>();

        buttons.put("NEW", new ButtonConfig(
                "NEW",
                "OBUIAPP_NewDoc",
                "NEW",
                true,
                "plus"
        ));
        buttons.put("SAVE", new ButtonConfig(
                "SAVE",
                "OBUIAPP_SaveRow",
                "SAVE",
                true,
                "save"
        ));
        buttons.put("DELETE", new ButtonConfig(
                "DELETE",
                "OBUIAPP_DeleteRow",
                "DELETE",
                !isNew,
                "trash"
        ));
        buttons.put("REFRESH", new ButtonConfig(
                "REFRESH",
                "OBUIAPP_RefreshData",
                "REFRESH",
                true,
                "refresh-cw"
        ));
        buttons.put("FIND", new ButtonConfig(
                "FIND",
                "OBUIAPP_Find",
                "FIND",
                true,
                "search"
        ));
        buttons.put("EXPORT", new ButtonConfig(
                "EXPORT",
                "OBUIAPP_ExportGrid",
                "EXPORT",
                true,
                "download"
        ));
        buttons.put("ATTACHMENTS", new ButtonConfig(
                "ATTACHMENTS",
                "OBUIAPP_Attachments",
                "ATTACHMENTS",
                true,
                "paperclip"
        ));
        buttons.put("GRID_VIEW", new ButtonConfig(
                "GRID_VIEW",
                "OBUIAPP_GridView",
                "GRID_VIEW",
                true,
                "grid"
        ));

        return buttons;
    }
```

2024-11-19 07:09 UTC, LuuchoRocha approved these changes

2024-11-19 07:09 UTC, LuuchoRocha commented on src/com/etendoerp/metadata/MetadataServlet.java
> +                throw new UnprocessableContentException("Invalid toolbar path");
actually this should be a not found 404 :nerd_face:

2024-11-19 12:39 UTC, LuuchoRocha approved these changes

2024-11-19 13:08 UTC, Agustin-Calderon approved these changes

2024-11-20 19:10 UTC, merged